Task 4 completed
brav3luk3/nctaskmanager pull request #4
Opened 2023-04-11 12:43 UTC by brav3luk3

AbstractTaskList was created. Common methods from ArrayTaskList and LinkedTaskList have been added to it.
The ListTypes class was created where the ARRAY and LINKED values ​​are located/
A TaskList Factory has been created with a method that, in accordance with the type parameter, returns an object of the ArrayTaskList or LinkedTaskList class

2023-04-11 12:48 UTC, captim requested changes

2023-04-11 12:48 UTC, captim commented on src/main/java/ua/edu/sumdu/j2se/semenyako/tasks/AbstractTaskList.java
> +        AbstractTaskList tasksInAInterval = getClass().getConstructor().newInstance();
Better to surround it "try catch block"

2023-04-11 12:48 UTC, captim commented on src/main/java/ua/edu/sumdu/j2se/semenyako/tasks/ListTypes.java
> +    }
Incorrect using of enum

2023-04-11 17:46 UTC, brav3luk3 commented on src/main/java/ua/edu/sumdu/j2se/semenyako/tasks/ListTypes.java
> +    }
Class was written according with task

2023-04-12 13:49 UTC, captim approved these changes

2023-04-12 13:49 UTC, merged